import 'package:flutter/foundation.dart';
import '../models/task_model.dart';
import '../repositories/task_repository.dart';

/// Task List ViewModel - Quản lý business logic cho danh sách tasks
/// MVVM Pattern: ViewModel chứa business logic và state management
class TaskListViewModel extends ChangeNotifier {
  final TaskRepository _repository = TaskRepository();

  // State
  List<TaskModel> _tasks = [];
  bool _isLoading = false;
  String? _errorMessage;

  // Getters
  List<TaskModel> get tasks => _tasks;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  /// Load tasks - CHỈ từ local database (API tắt tạm để test)
  Future<void> loadTasks() async {
    _setLoading(true);
    _errorMessage = null;

    try {
      // Dùng lightweight mode để tránh lag UI
      // Chỉ load tasks chính, không load subtasks/attachments/reminders
      _tasks = await _repository.getTasksFromLocalLight(limit: 100);
    } catch (e) {
      _errorMessage = 'Failed to load tasks: $e';
    } finally {
      _setLoading(false);
    }
  }

  /// Thêm task mới
  Future<bool> addTask({
    required String title,
    required String description,
    String status = 'Pending',
    String priority = 'Medium',
    String category = '',
    DateTime? dueDate,
  }) async {
    try {
      final now = DateTime.now();
      final task = TaskModel(
        id: 0, // Will be auto-generated by database
        title: title,
        description: description,
        status: status,
        createdAt: now,
        updatedAt: now,
      );

      final taskId = await _repository.addTask(task);
      if (taskId > 0) {
        await loadTasks(); // Reload to show new task
        return true;
      }

      return false;
    } catch (e) {
      _errorMessage = 'Failed to add task: $e';
      notifyListeners();
      return false;
    }
  }

  /// Xóa task
  Future<bool> deleteTask(int taskId) async {
    try {
      final success = await _repository.deleteTaskFromLocal(taskId);

      if (success) {
        _tasks.removeWhere((task) => task.id == taskId);
        notifyListeners();
        return true;
      }
      return false;
    } catch (e) {
      _errorMessage = 'Failed to delete task: $e';
      notifyListeners();
      return false;
    }
  }

  /// Toggle task status (Pending <-> Completed)
  Future<bool> toggleTaskStatus(TaskModel task) async {
    try {
      final newStatus = task.status == 'Completed' ? 'Pending' : 'Completed';

      // Tạo task mới với status đã thay đổi
      final updatedTask = TaskModel(
        id: task.id,
        title: task.title,
        description: task.description,
        status: newStatus,
        createdAt: task.createdAt,
        updatedAt: DateTime.now(),
      );

      final success = await _repository.updateTask(updatedTask);

      if (success) {
        await loadTasks(); // Reload to show updated status
        return true;
      }
      return false;
    } catch (e) {
      _errorMessage = 'Failed to toggle task status: $e';
      notifyListeners();
      return false;
    }
  }

  /// Private helper to set loading state
  void _setLoading(bool loading) {
    _isLoading = loading;
    notifyListeners();
  }
}
