// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12x-JN5XQaCSQ_fQp7kvh3BY4KOzKpCg',
    appId: '1:139858305764:web:6064d27e26d1edf99c82f1',
    messagingSenderId: '139858305764',
    projectId: 'uth-86ede',
    authDomain: 'uth-86ede.firebaseapp.com',
    storageBucket: 'uth-86ede.firebasestorage.app',
    measurementId: 'G-ZFR6H05EGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMka8cWDDDZQ7LyIgzsYR9Bi98CoNSjc',
    appId: '1:139858305764:android:e976e0bd416bc2df9c82f1',
    messagingSenderId: '139858305764',
    projectId: 'uth-86ede',
    storageBucket: 'uth-86ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5faxsbpL33p768S-cywUzzAXhnqTJX0',
    appId: '1:139858305764:ios:755e7f2e0c2916469c82f1',
    messagingSenderId: '139858305764',
    projectId: 'uth-86ede',
    storageBucket: 'uth-86ede.firebasestorage.app',
    iosBundleId: 'com.example.btapNavigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5faxsbpL33p768S-cywUzzAXhnqTJX0',
    appId: '1:139858305764:ios:755e7f2e0c2916469c82f1',
    messagingSenderId: '139858305764',
    projectId: 'uth-86ede',
    storageBucket: 'uth-86ede.firebasestorage.app',
    iosBundleId: 'com.example.btapNavigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA12x-JN5XQaCSQ_fQp7kvh3BY4KOzKpCg',
    appId: '1:139858305764:web:dd3737d6687271849c82f1',
    messagingSenderId: '139858305764',
    projectId: 'uth-86ede',
    authDomain: 'uth-86ede.firebaseapp.com',
    storageBucket: 'uth-86ede.firebasestorage.app',
    measurementId: 'G-JKPJ8EL1V2',
  );
}
